apiVersion: v1
kind: Service
metadata:
  name: cv-service
  labels:
    app: cv-onepage
spec:
  type: NodePort
  selector:
    app: cv-onepage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
