server:
  log_level: info

prometheus:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
  configs:
    - name: integrations
      scrape_configs:
        - job_name: 'node'
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'docker'
          static_configs:
            - targets: ['localhost:9323']
        - job_name: 'k3s'
          kubernetes_sd_configs:
            - role: node
      remote_write:
        - url: "https://prometheus-blocks-prod-eu-central-0.grafana.net/api/prom/push"
          basic_auth:
            username: "apikey"
            password: "glc_eyJvIjoiMTQyOTE1MyIsIm4iOiJhZ2VudC1tZXRyaWNzLWFhIiwiayI6IkdOM2o0SDRJMGE3aVE3NldJdjZVSU0yMCIsIm0iOnsiciI6InByb2QtZXUtY2VudHJhbC0wIn19q"  # ton token exact
      
integrations:
  node_exporter:
    enabled: true
  cadvisor:
    enabled: true
